### PR TITLE
fix(main): sync cert for cert cmd

### PR DESCRIPTION
**Pull request by cuisongliu**
### Summary
🐛🔄🔐

Fix certificate and kubeconfig synchronization bug for master nodes. Refactor `pkg/runtime/kubernetes/certs.go` to use a new function `k.syncCert` that generates and copies certificates and kubeconfigs for all master nodes.

> _Oh we're the masters of the cluster, we keep it running smooth_
> _We sync the certs and kubeconfigs, we know just what to do_
> _We use the function `k.syncCert`, it does the job for all_
> _And when we add new SANs or nodes, we heed the captain's call_

### Walkthrough
*  Add a new function `k.syncCert` to synchronize the certificates and kubeconfigs of all the master nodes after adding a new SAN to the API server certificate ([link](https://github.com/labring/sealos/pull/3891/files?diff=unified&w=0#diff-9f497f2c9f2d5b73bc039218ef7ac3801dcd3d788a1d4f6cb23b3c4706cb52ffR59) in `pkg/runtime/kubernetes/certs.go`)

### CODE REVIEW

**Comment by yangxggo** [comment]
2941695010589_ pic

**Comment by yangxggo** [comment]
2951695010606_ pic

**Comment by yangxggo** [comment]
2961695010635_ pic

**Comment by yangxggo** [comment]
2971695010726_ pic

**Comment by yangxggo** [comment]
tested

**Review by zzjin — APPROVED** [review]

**Pull request merged**
