### PR TITLE
Update user.md

### PR DESCRIPTION
**Pull request by 1oda**
修改错别字“几遍私有云”，改为“即便私有云”

### CODE REVIEW

**Comment by fanux** [comment]
@1oda `git commit -s --amend && git push` signoff this PR

**Review by 1oda — COMMENTED** [review]
修改错别字“几遍私有云”，改为“即便私有云”

**Comment by 1oda** [comment]
use "git commit -s --amend && git push"
autoadded "Signed-off-by: tang <296429819@qq.com>"
still push failed with "fatal: Authentication failed for 'https://github.com/labring/sealos.git/"

**Comment by zzjin** [comment]
try `git commit -s --amend && git push -f`

**Pull request closed without merging**
