### PR TITLE
feature(main): Support configuration file custom vip

### PR DESCRIPTION
**Pull request by cuisongliu**
https://github.com/labring/sealos/issues/2059

Signed-off-by: cuisongliu <cuisongliu@qq.com>

### CODE REVIEW

**Comment by cuisongliu** [comment]
However, we need to wait for the cluster image to be updated.  https://github.com/labring/cluster-image/commit/7296c1807f07d9cb5114579a100f8f8073a3b473

**Comment by fanux** [comment]
Add docs about how to config VIP, using image label means must build the image?

**Comment by cuisongliu** [comment]
> Add docs about how to config VIP, using image label means must build the image?

sealos run --env defaultVIP=xxxx. , but need we rebuild all image

**Comment by cuisongliu** [comment]
sealos run docker.io/labring/kubernetes:v1.23 --env defaultVIP=10.103.97.2

**Comment by fanux** [comment]
Got it, please add a document in docs dir, 《how to config master loadbalance VIP》

**Comment by cuisongliu** [comment]
> Got it, please add a document in docs dir, 《how to config master loadbalance VIP》

Yes, I need to complete the document after the test.

**Review by fanux — APPROVED** [review]

**Pull request merged**
