### PR TITLE
feat: add and delete master or worker nodes with different ssh settings

### PR DESCRIPTION
**Pull request by yangxggo**
feature: 
support add and delete master or worker nodes with different ssh settings.

for example:
sealos add --masters 10.10.12.19 -p test@2
sealos add --nodes 10.10.12.17 -p test@4
sealos add --nodes 10.10.12.32 -p test@3

and delete command does not need to specify the different password:
sealos delete --masters 10.10.12.19 --nodes 10.10.12.17,10.10.12.32

my solution:
  1. set the ssh configs in hosts.ssh if the hosts have different configs from the cluster common one.
  2. in add nodes,  use hosts.ssh if it is not nil, or use the common ssh.
  3. in delete nodes,  deliver both desired spec and current spec to the "Runtime", IN CASE THAT the deleting nodes have different ssh configs.

### CODE REVIEW

**Comment by yangxggo** [comment]
I will submit the test report later

**Comment by yangxggo** [comment]
issue #3492

**Comment by fengxsong** [comment]
IMO, it's unnecessary to modify the interface https://github.com/labring/sealos/blob/dd81a8183039d0724fa060a6bc98c7ecaf6b8dff/pkg/bootstrap/context.go#L29 and https://github.com/labring/sealos/blob/dd81a8183039d0724fa060a6bc98c7ecaf6b8dff/pkg/filesystem/filesystem.go#L25, please checkout https://github.com/labring/sealos/blob/main/pkg/ssh/clusterclient.go

**Comment by yangxggo** [comment]
> IMO, it's unnecessary to modify the interface
> 
> https://github.com/labring/sealos/blob/dd81a8183039d0724fa060a6bc98c7ecaf6b8dff/pkg/bootstrap/context.go#L29
> 
> and
> https://github.com/labring/sealos/blob/dd81a8183039d0724fa060a6bc98c7ecaf6b8dff/pkg/filesystem/filesystem.go#L25
> 
> , please checkout https://github.com/labring/sealos/blob/main/pkg/ssh/clusterclient.go

let me have a look

**Review by fengxsong — APPROVED** [review]
LGTM

**Review by cuisongliu — APPROVED** [review]

**Pull request merged**
