### PR TITLE
fix: error in inspect function when the image is in format "docker-archive:./xxx.tar"

### PR DESCRIPTION
**Pull request by 24sama**
Fix: #2577

When the user specifies the image as `xxx.tar` format, the previous code logic is run. This code references:
https://github.com/labring/sealos/blob/6ab3a669682579ab1dc8852708cc8997e8af0d92/cmd/sealos/cmd/run.go#L116

### CODE REVIEW

**Comment by fengxsong** [comment]
# L212-L224 remove retry package
```
	rawManifest, _, err = src.GetManifest(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("error retrieving manifest for image: %w", err)
	}

	config, err = img.OCIConfig(ctx)
	if err != nil {
		return nil, fmt.Errorf("error reading OCI-formatted configuration data: %w", err)
	}
```

# 255-L285 not only deal with tar file type.
```
	parseSource := func(s string) (types.ImageSource, error) {
		ref, err := transport.ParseReference(s)
		if err != nil {
			return nil, err
		}
		return ref.NewImageSource(ctx, sc)
	}
	var (
		src types.ImageSource
		err error
	)
	switch transport.Name() {
	case TransportContainersStorage:
		names, err := shortnames.ResolveLocally(sc, imgName)
		if err != nil {
			return nil, nil, fmt.Errorf("error resolve shortname %s: %w", imgName, storage.ErrImageUnknown)
		}
		for _, name := range names {
			src, err = parseSource(name.String())
			if err == nil {
				break
			}
		}
	default:
		src, err = parseSource(imgName)
	}
	if err != nil {
		return nil, nil, fmt.Errorf("error parsing image name %q: %w", imgName, err)

```

**Comment by fengxsong** [comment]
`shortnames` is a very interesting feature but we need to use it carefully.

**Comment by 24sama** [comment]
> * L212-L224 remove retry package
> 
> ```
> 	rawManifest, _, err = src.GetManifest(ctx, nil)
> 	if err != nil {
> 		return nil, fmt.Errorf("error retrieving manifest for image: %w", err)
> 	}
> 
> 	config, err = img.OCIConfig(ctx)
> 	if err != nil {
> 		return nil, fmt.Errorf("error reading OCI-formatted configuration data: %w", err)
> 	}
> ```
> 
> * 255-L285 not only deal with tar file type.
> 
> ```
> 	parseSource := func(s string) (types.ImageSource, error) {
> 		ref, err := transport.ParseReference(s)
> 		if err != nil {
> 			return nil, err
> 		}
> 		return ref.NewImageSource(ctx, sc)
> 	}
> 	var (
> 		src types.ImageSource
> 		err error
> 	)
> 	switch transport.Name() {
> 	case TransportContainersStorage:
> 		names, err := shortnames.ResolveLocally(sc, imgName)
> 		if err != nil {
> 			return nil, nil, fmt.Errorf("error resolve shortname %s: %w", imgName, storage.ErrImageUnknown)
> 		}
> 		for _, name := range names {
> 			src, err = parseSource(name.String())
> 			if err == nil {
> 				break
> 			}
> 		}
> 	default:
> 		src, err = parseSource(imgName)
> 	}
> 	if err != nil {
> 		return nil, nil, fmt.Errorf("error parsing image name %q: %w", imgName, err)
> ```

Thanks for your review, I have applied your suggestions.

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/pull/2583  , close this pr . using @fengxsong pr ?

**Comment by 24sama** [comment]
> #2583 , close this pr . using @fengxsong pr ?

I commented on that PR, that has a small bug that needs to fix. Maybe we can merge this PR, and that one just need to do a rebase operation.

**Comment by cuisongliu** [comment]
> > #2583 , close this pr . using @fengxsong pr ?
> 
> I commented on that PR, that has a small bug that needs to fix. Maybe we can merge this PR, and that one just need to do a rebase operation.

/cc @fengxsong

**Review by cuisongliu — APPROVED** [review]

**Pull request merged**
