### PR TITLE
docs: add install example for tailchat

### PR DESCRIPTION
**Pull request by moonrailgun**
A problem is i cannot preview results in local machine.

Because the source and real website is in two repo.

And i cannt append i18n for new category in `code.json`. So why make everything together?

-------

### Summary
📝🌐💬

This pull request adds a new example document and its Chinese translation on how to install Tailchat, an open source IM application, on Sealos using the UI and the terminal. It also updates the sidebar and the README file to include the new document.

> _`Tailchat` on `Sealos`_
> _A guide for social apps_
> _Winter loneliness_

### Walkthrough
* Create a new document that provides a step-by-step guide on how to install Tailchat on Sealos using the UI and the terminal ([link](https://github.com/labring/sealos/pull/3302/files?diff=unified&w=0#diff-ddc59ad9d28c7c2f503457bcb8cbb5b7090bd432fd50778b551c012907f47a34R1-R149))
* Translate the document into Chinese and place it in the corresponding folder ([link](https://github.com/labring/sealos/pull/3302/files?diff=unified&w=0#diff-5eeff1732b0403768d6c285492b07cb9765716ec670889bf722bf6cf8e1a96ccR1-R179))
* Add a new category called `social-communication` to the sidebar configuration file and link to the index of the documents in the `examples/social-communication` folder ([link](https://github.com/labring/sealos/pull/3302/files?diff=unified&w=0#diff-a909b3a475bca2cfc85fa4980cf84f029a120986b61049c13a1bcfedb2c568d5R79-R93))
* Add a link to the Tailchat installation document to the section `🚀 在 Sealos 上快速部署分布式应用` in the `README_zh.md` file ([link](https://github.com/labring/sealos/pull/3302/files?diff=unified&w=0#diff-bc53aca037f8d406f619f15cf2c5c905a7a61f81f89cab98dd52f7ff65725f6eR42))

### CODE REVIEW

**Comment by bxy4543** [comment]
resolve conflicting

**Comment by fanux** [comment]
Once i18n is online, you can simply replace the English images.

**Comment by moonrailgun** [comment]
> resolve conflicting

DONE, pls review again. thx

**Comment by cuisongliu** [comment]
rebase code .

**Comment by moonrailgun** [comment]
i18n image has been updated, and rebase up to main branch. 

please review it again, thx

**Comment by moonrailgun** [comment]
new i18n image has been replaced, has code has been rebase on latest branch.

pls review it again, thx

**Pull request merged**
