### PR TITLE
feat: grouping subcommands

### PR DESCRIPTION
**Pull request by fengxsong**
feat #2816 

The changes to note are as follows:

- `buildah.RegisterRootCommand` now only regsiter root command and wrap the pre/post persistent function
- adding images commands should call `rootCmd.AddCommands` explicitly

### CODE REVIEW

**Comment by zzjin** [comment]
Is here need some api doc updates?

**Comment by zzjin** [comment]
copilot:all

**Comment by fengxsong** [comment]
> Is here need some api doc updates?

I've added changes to be aware in the comment.

**Comment by cuisongliu** [comment]
copilot:all

**Review by cuisongliu — APPROVED** [review]

**Pull request merged**
