### PR TITLE
Using module to simpler vsc source tree. Closes #1771

### LINKED ISSUE #1171: Feature: Cleanup vendor dir to keep vsc clean and thin.
Current source tree has all 3rd module install locally but we can use go module to keep things simpler.

Complete this feature through:
1. Delete vendor dir
2. Update lint requires
3. Update gitignore to iognore genareted files.
4. Update `Makefile` to gen required file.

### LINKED ISSUE #1771: BUG:  sealos create error with `default: image not known`
**Which command or component**

sealos creae

sealos versino v4.1.3

**The Description of the bug**

Describe the bug.

**How to reproduce（pictures can be attached if necessary）**
```
root@ubuntu:~# sealos create mysql:8.0
Resolving "mysql" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull docker.io/library/mysql:8.0...
Getting image source signatures
Copying blob f5227e0d612c done  
Copying blob 95753aff4b95 done  
Copying blob a1fa3bee53f4 done  
Copying blob a44b358d7796 done  
Copying blob 051f419db9dd done  
Copying blob 7627573fa82a done  
Copying blob b4b4368b1983 done  
Copying blob d5358a7f7d07 done  
Copying blob f26212810c32 done  
Copying blob 435e8908cd69 done  
Copying blob d803d4215f95 done  
Copying config 43fcfca077 done  
Writing manifest to image destination
Storing signatures
43fcfca0776df8e192d1647da2866237fbd9f8e875fb496e4ca887369b2dd995
default: image not known
Error: exit status 125
Usage:
  sealos create [flags]

Examples:

create a mysql cluster:
        sealos create mysql:8.0
with custom cluster name:
        sealos create mysql:8.0 -c mysql


Flags:
  -c, --cluster-name string   name of cluster to be created (default "default")
  -h, --help                  help for create

Global Flags:
      --cluster-root string   cluster root directory (default "/var/lib/sealos")
      --debug                 enable debug logger

exit status 125
```

**What you expected to happen**

i want know what is `sealos create`, what it used for?

**Operating environment**

- Docker version:   eg. 19.03
- Kubernetes version: eg.kube1.16.tar.gz
- Sealos version: v4.1.3
- Operating system: ubuntu
- Runtime environment:  
- Cluster size: eg 3 master, 3 node
- Additional information: istio, dashboard ...

### PR DESCRIPTION
**Pull request by zzjin**
1. remove versioned `vendor` dir.
2. fix `make lint` usage

### CODE REVIEW

**Comment by fanux** [comment]
@zzjin have you test the makefile?

**Comment by cuisongliu** [comment]
> @zzjin have you test the makefile?

I don’t think it‘s necessary to delete the vendor.

**Comment by zzjin** [comment]
> 

yes, all command tested fine.

**Comment by zzjin** [comment]
> > @zzjin have you test the makefile?
> 
> I don’t think it‘s necessary to delete the vendor.

Having tens of thousands of other repo's files locally seems not necessary, since those files never need to be changed, and *must not* changed.

`go.mod` and `go.sum` can keep and lock required repo versions.

**Comment by cuisongliu** [comment]
> > > @zzjin have you test the makefile?
> 
> > 
> 
> > I don’t think it‘s necessary to delete the vendor.
> 
> 
> 
> Having tens of thousands of other repo's files locally seems not necessary, since those files never need to be changed, and *must not* changed.
> 
> 
> 
> `go.mod` and `go.sum` can keep and lock required repo versions.

However, if the user may pull go mod due to a network problem, if the vendor is used, there will be no problem.

**Comment by cuisongliu** [comment]
If I don‘t think it’s necessary because of too many files, it‘s just that the first time to pull code slowly, it will actually have no impact on compilation or running in the future.

**Comment by fanux** [comment]
I think the vendor can delete and keep it, if there is no problem with the makefile changes in this PR, it can be merged  @cuisongliu

**Comment by zzjin** [comment]
> 
 network problem can be done by using proxy like `goproxy.cn`

**Comment by zzjin** [comment]
> If I don‘t think it’s necessary because of too many files, it‘s just that the first time to pull code slowly, it will actually have no impact on compilation or running in the future.

The first time pull/clone is not the main problem. and codespaces need to install some libs like `libbtrfs` to start build(among like go modules)

However, when someone changed the code, add/delete one of 3rd repo, or upgrade repo's version, the changelog will be withn thouands of files and  make the code review harder with large codebase disturbed

**Comment by fanux** [comment]
It will be more convenient for developers to retain the code generated by genrate, and kubernetes also retains this.   I'm in favor of removing vendor

**Comment by cuisongliu** [comment]
1. generator code Keep it, because this part of the code will be used during the development process.
2. Don't modify the code from kubernetes copy. That part of the code is dependent on kubeadm.
3. Generating code requires manual operation.
4. delete vendor

**Comment by fanux** [comment]
> > If I don‘t think it’s necessary because of too many files, it‘s just that the first time to pull code slowly, it will actually have no impact on compilation or running in the future.
> 
> The first time pull/clone is not the main problem. and codespaces need to install some libs like `libbtrfs` to start build(among like go modules)
> 
> However, when someone changed the code, add/delete one of 3rd repo, or upgrade repo's version, the changelog will be withn thouands of files and make the code review harder with large codebase disturbed

Agree~ 

And could you add the generated code back? If not  developer need much more dependencies(generator) to build the project.

**Comment by zzjin** [comment]
deal. will update asap.

**Comment by zzjin** [comment]
Done.

**Comment by cuisongliu** [comment]
conversion-gen  You can add it.

**Review by cuisongliu — APPROVED** [review]

**Pull request merged**
