### PR TITLE
ci: enable CGO for building sealos

### PR DESCRIPTION
**Pull request by SignorMercurio**

### CODE REVIEW

**Comment by fanux** [comment]
image

@SignorMercurio this PR fixed this issue?

And `make build` on mac os success?

**Comment by SignorMercurio** [comment]
@fanux This PR should eliminate all "driver not supported" errors because CGO is enabled. `make build` on linux amd64/arm64 will always success while on macOS the result is undefined.

**Review by berlinsaint — COMMENTED** [review]
lgtm

**Review by berlinsaint — APPROVED** [review]
/approved

**Pull request merged**
